pipeline {
    agent any
    environment {
        BITBUCKET_COMMON_CREDS = credentials('jenkins-bitbucket-common-creds')
    }
    stages {
        stage('build') {
            steps {
                sh 'npm --version'
                sh 'ruby --version'
                sh 'python --version'
                sh 'php --version'
                sh 'pwd'
            }
        }
        stage('Deploy') {
            steps {
                retry(3) {
                    sh 'echo "Hello World"'
                }
                
                timeout(time:5, unit: 'SECONDS') {
                    echo "end"
                }
            }
        }
        stage('Deloy-2') {
            steps {
                timeout(time:5, unit: 'SECONDS') {
                    retry(3) {
                        sh 'echo "Hello New World"'
                    }
                }
            }
        }
        stage('usernames and passwords') {
            steps {
                echo 'uer psw'
            }
        }
    }
    post {
        always {
            echo 'I will allways return!'
        }
        success {
            echo 'Run success!'
        }
        failure {
            echo 'Run fail!'
        }
        unstable {
            echo 'Run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}