pipeline {
    agent any
    // environment {
    //     BITBUCKET_COMMON_CREDS = credentials('jenkins-bitbucket-common-creds')
    // }
    parameters {
        credentials credentialType: 'com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey', defaultValue: 'ce9fe0a2-ce19-406a-b825-5c13cff6d8e6', description: 'SSH credential used to pull & push your git updates.Please make sure this credential has access to all the repositories being handled in the proceeded processes.', name: 'Git_Credential_Id', required: false
        credentials credentialType: 'com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl', defaultValue: 'def2d46f-8088-43a2-ab07-84e0dd043d6a', description: '上传IPA到AppStore的apple_id用户名和密码', name: 'apple_id', required: true
    }
    stages {
        stage('build') {
            steps {
                sh 'npm --version'
                sh 'ruby --version'
                sh 'python --version'
                sh 'php --version'
                sh 'pwd'
            }
        }
        stage('Deploy') {
            steps {
                retry(3) {
                    sh 'echo "Hello World"'
                }
                
                timeout(time:5, unit: 'SECONDS') {
                    echo "end"
                }
            }
        }
        stage('Deloy-2') {
            steps {
                timeout(time:5, unit: 'SECONDS') {
                    retry(3) {
                        sh 'echo "Hello New World"'
                    }
                }
            }
        }
        stage('Jenkins file') {
            steps {
                echo "Running  on ${env.JENKINS_URL}" 
            }
        }
        stage('usernames and passwords') {
            steps {
                echo 'uer psw'
            }
        }
        stage('Deploy - Staging') {
            steps {
                echo 'Staging Time'
            }
        }
        stage('Sanity check') {
            steps {
                // input "Does the staging environment look ok?"
                withCredentials([usernamePassword(credentialsId: params.apple_id, passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh(label: "Uploadting ipa to app store", script: "sh jenkins/upload_to_app_store.sh ${ipa_path} ${username} ${password}")
                    echo "username - ${username}"
                    echo "password - ${password}"
                }
                // echo "Git - ${params.Git_Credential_Id}"
                // echo "apple id - ${params.apple_id}"
            }
        }
        stage('Deploy - Production') {
            steps {
                echo 'Production Time'
            }
        }
    }
    post {
        always {
            echo 'I will allways return!'
        }
        success {
            echo 'Run success!'
        }
        failure {
            echo 'Run fail!'
        }
        unstable {
            echo 'Run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}